# Travis file
# See https://docs.travis-ci.com/user/languages/r/

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - pip install --user retinasdk

python:
  - "3.6"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    packages:
      - libxml2-dev
