# Create company description dataset

company_descriptions <- list(
  "unilever" = list(
    "desc" = "Unilever PLC, incorporated on June 21, 1894, is a fast-moving consumer goods (FMCG) company. The Company's segments include Personal Care, which primarily includes sales of skin care and hair care products, deodorants and oral care products; Foods, which primarily includes sales of soups, bouillons, sauces, snacks, mayonnaise, salad dressings, margarines and spreads; Home Care, which primarily includes sales of home care products, such as powders, liquids and capsules, soap bars and a range of cleaning products, and Refreshment, which primarily includes sales of ice cream and tea-based beverages. The Company's geographical segments include Asia/AMET/RUB, The Americas and Europe. The Company operates in more than 100 countries, selling its products in more than 190 countries. The Company operates approximately 310 factories in over 70 countries. It operates a network of over 400 warehouses globally.
The Company's personal brands include Axe, Dove, Lux, Rexona and Sunsilk. And Axe, known as Lynx in the United Kingdom, Ireland and Australia includes shower gels and shampoos with the same seductive scents. It offers daily fragrances, hair styling, body washes and antiperspirants. In its deodorants business, the Company offers Rexona Antibacterial Defence, which is available in more than 40 countries. Dove offers a range of products, including Body Washes, Hand and Body Lotions, Facial Cleansers, Deodorants, Shampoos, Conditioners and Hair Styling products. In addition to Dove, Personal Care includes Lifebuoy and Signal. Its brands also include TRESemme and Zendium. Its skin care brands include Dermalogica; Murad; Kate Somerville, and REN. The Company's Foods brands include Knorr and Hellmann's. Alongside global brands, the Company also has local brands, such as Bango in Indonesia, Robertson's in South Africa and Kissan in India. Its Home Care brands include Dirt is Good and Surf, as well as other household names, including Comfort, Sunlight and Domestos, and its water purification brand, Pureit. Its Refreshment brands include Heartbrand (Wall's), Magnum, Lipton, Ben & Jerry's, and Breyer. Lipton offers an array of tea-based drinks, from leaf tea to tea bags, Lipton Ice Tea soft drinks, zero calorie infusions and healthy green tea.
    The Company's brands around the world include Blue Band, Bonella, County Crock, Doriana, Dorina, Imperial, La Perfecta, Maizena, Milda, Mirasol, Planta, Planta Fin, Primavera, Rama, Sana, Stork, Tulipan and Vitam. The Company's Domestos, Domex, Glorix, Vim, Promax and Klinex are available in over 35 countries. The range includes liquid thick bleach, multipurpose spray, limescale removers, fragranced toilet rim blocks and wipes. It offers a range of ice creams brands, including Magnum, Cornetto, Solero, Viennetta and Carte d'Or. Its products are sold in more than 40 countries around the world, under different local names. The Hellmann's brand family consist of Hellmann's, Amora, Calve and Wish-Bone. Its brands cover a range of products from its mayonnaise to ketchup, mustard, salad dressings and table sauces. It offers a range of liquid hand washes and hand sanitizers to ensure daily hygiene and freshness for the entire family. Omo is sold as Persil, Skip, Breeze, Ala, Wisk, Surf and Rinso in some parts of the world. The Surf brand name products are available in Europe, Latin America, Asia, Asia Pacific and Africa with a range, including bars, powders, liquids and capsules.",
    "name" = "Unilever PLC",
    "ticker" = "UL.N",
    "url" = "https://www.reuters.com/finance/stocks/overview/UL.N"
  ),
  "ahold" = list(
    "desc" = "Koninklijke Ahold Delhaize N.V., formerly Koninklijke Ahold N.V., is engaged in the operation of retail stores in Europe and the United States. The Company's segments are Ahold USA, Delhaize America, The Netherlands, Belgium, and Central and Southeastern Europe (CSE). In addition, Other retail, consists of Ahold Delhaize's unconsolidated joint ventures JMR - Gestao de Empresas de Retalho, SGPS, S.A. (JMR) and P.T. Lion Super Indo, LLC (Super Indo), and Ahold Delhaize's Global Support Office. JMR operates food retail stores in Portugal under the brand name Pingo Doce. The Company's Ahold USA segment includes Stop & Shop New England, Stop & Shop New York Metro, Giant Landover, Giant Carlisle and Peapod. The Company's Delhaize America segment includes brands, such as Food Lion and Hannaford. The Food Lion brand's market areas include Delaware, Georgia, Maryland, Pennsylvania, Tennessee, West Virginia, Kentucky, North Carolina, South Carolina and Virginia.",
    "name" = "Koninklijke Ahold Delhaize N.V.",
    "ticker" = "AD.AS",
    "url" = "https://www.reuters.com/finance/stocks/company-profile/AD.AS"
  ),
  "ing" = list(
    "desc" = "ING Groep N.V. (ING), incorporated on January 21, 1991, is a financial institution. The Company offers banking services. The Company's segments include Retail Netherlands, which offers current and savings accounts, business lending, mortgages and other consumer lending in the Netherlands; Retail Belgium, which offers products that are similar to those in the Netherlands; Retail Germany, which offers current and savings accounts, mortgages and other customer lending; Retail Other, which offers products that are similar to those in the Netherlands, and Wholesale Banking, which offers wholesale banking activities (a full range of products from cash management to corporate finance), real estate and lease. The Company's Retail Banking business lines provide products and services to individuals, small and medium-sized enterprises (SMEs) and mid-corporates.
The Retail Netherlands segment recognizes income from retail and private banking activities in the Netherlands, including the SME and mid-corporate segments. The Retail Belgium segment recognizes income from retail and private banking activities in Belgium, including the SME and mid-corporate segments. The Retail Germany segment recognizes income from retail and private banking activities in Germany. The Retail other segment recognizes income from retail banking activities in the rest of the world, including the SME and mid-corporate segments in specific countries. The Wholesale Banking segment recognizes income from wholesale banking activities, real estate and lease. ING Bank's subsidiary in the United States is ING Financial Holdings Corporation, which offers a range of financial products, including lending and financial markets products. ING's banking activities in Australia are undertaken by ING Bank (Australia) Limited (trading as ING Direct) and ING Bank NV Sydney Branch.
    The Company competes with ABN AMRO Bank and Rabobank.",
    "name" = "ING Groep NV",
    "ticker" = "ING",
    "url" = "https://www.reuters.com/finance/stocks/overview/ING"
  ),
  "Alphabet" = list(
    "desc" = "Alphabet Inc., incorporated on July 23, 2015, is a holding company. The Company's businesses include Google Inc. (Google) and its Internet products, such as Access, Calico, CapitalG, GV, Nest, Verily, Waymo and X. The Company's segments include Google and Other Bets. The Google segment includes its Internet products, such as Search, Ads, Commerce, Maps, YouTube, Google Cloud, Android, Chrome and Google Play, as well as its hardware initiatives. The Google segment is engaged in advertising, sales of digital content, applications and cloud offerings, and sales of hardware products. The Other Bets segment is engaged in the sales of Internet and television services through Google Fiber, sales of Nest products and services, and licensing and research and development (R&D) services through Verily.
    Google is engaged in investing in infrastructure, data management, analytics and artificial intelligence (AI). The Company offers Google Assistant, which allows users to type or talk with Google in a natural conversational way to help them get things done; Google Maps, which helps users navigate to a store while showing them current traffic conditions, and Google Photos, which helps users store and organize all of their photos. The Company invests in platforms, such as Chrome browser, Android mobile operating system, Chrome operating system and Daydream virtual reality platform, as well as its hardware devices, such as the Pixel phone and Google Home.
    The Company provides advertisers with tools that help them attribute and measure their advertising campaigns across screens. Its advertising solutions help a range of companies grow their businesses, and it offers a range of products across screens and devices. For performance advertisers, AdWords, its primary auction-based advertising program, helps create text-based advertisements that appear on Google properties and the properties of Google Network Members. In addition, Google Network Members use its AdSense program to display relevant advertisements on their properties, generating revenues when site visitors view or click on the advertisements. The Company also offers advertisement technology platform for brand advertisers, agencies, and publishers to help their digital marketing businesses.
    The Company competes with Microsoft, Yahoo, Yandex, Baidu, Naver, Seznam, Amazon, eBay, Kayak, LinkedIn, WebMD, Facebook, Twitter, Criteo, AppNexus, Netflix, Hulu and Apple.",
    "name" = "Alphabet Inc",
    "ticker" = "GOOGL.OQ",
    "url" = "https://www.reuters.com/finance/stocks/company-profile/GOOGL.OQ"
  ),
  "apple" = list(
    "desc" = "Apple Inc., incorporated on January 3, 1977, designs, manufactures and markets mobile communication and media devices, personal computers and portable digital music players. The Company sells a range of related software, services, accessories, networking solutions and third-party digital content and applications. The Company's segments include the Americas, Europe, Greater China, Japan and Rest of Asia Pacific. The Americas segment includes both North and South America. The Europe segment includes European countries, India, the Middle East and Africa. The Greater China segment includes China, Hong Kong and Taiwan. The Rest of Asia Pacific segment includes Australia and the Asian countries not included in the Company's other operating segments. The Company's products and services include iPhone, iPad, Mac, iPod, Apple Watch, Apple TV, a portfolio of consumer and professional software applications, iPhone OS (iOS), OS X and watchOS operating systems, iCloud, Apple Pay and a range of accessory, service and support offerings.
The Company sells and delivers digital content and applications through the iTunes Store, App Store, Mac App Store, television APP Store, iBooks Store and Apple Music (collectively Internet Services). The Company sells its products through its retail stores, online stores and direct sales force through third-party cellular network carriers, wholesalers, retailers and value-added resellers. The Company sells a range of third-party Apple compatible products, including application software and accessories through its retail and online stores. The Company sells to consumers, small and mid-sized businesses and education, enterprise and government customers.
    iPhone is the Company's line of smartphones based on its iOS operating system. iPhone includes Siri, a voice activated intelligent assistant, and Apple Pay and touch ID on qualifying devices. The Company offers iPhone 7 and 7 Plus, featuring new camera systems, stereo speakers and water and dust resistance. The Company also sells iPhone SE, which has a four-inch Retina display. iPhone works with the iTunes Store, App Store, iBooks Store and Apple Music for purchasing, organizing and playing digital content and applications. iPad is the Company's line of multi-purpose tablets based on its iOS operating system. iPad includes iPad Pro, iPad Air and iPad mini. Mac is the Company's line of desktop and portable personal computers based on its macOS operating system. The Company's desktop computers include iMac, 21.5 inches iMac with Retina 4K display, 27 inches iMac with Retina 5K display, Mac Pro and Mac mini. The Company's portable computers include MacBook, MacBook Air, MacBook Pro and MacBook Pro with Retina display.
    Apple TV connects to consumers televisions (TVs) and enables them to access digital content directly for streaming high definition video, playing music and games, and viewing photos. Content from Apple Music and other media services is also available on Apple TV. Apple TV allows streaming digital content from Mac and Windows personal computers through Home Share and from compatible Mac and iOS devices through AirPlay. The Company's Apple TV runs on its tvOS operating system and is based on applications built for the television. Additionally, the Apple TV remote features Siri, allowing users to search and access content with their voice. Apple Watch is a personal electronic device that combines the watchOS user interface and technologies created specifically for a smaller device, including the Digital Crown, a navigation tool that allows users to seamlessly scroll, zoom and navigate, and force touch, a technology that senses the difference between a tap and a press and allows users to access controls within applications. Apple Watch enables users to communicate in new ways from their wrist, track their health and fitness through activity and workout applications, and includes Siri and Apple Pay. The Company offers Apple Watch Series 2, featuring fitness and health capabilities.
    iPod is the Company's line of portable digital music and media players, which includes iPod touch, iPod nano and iPod shuffle. All iPods work with iTunes to purchase and synchronize content. iPod touch, based on the Company's iOS operating system, is a flash-memory-based iPod that works with the iTunes Store, App Store and iBooks Store for purchasing and playing digital content and applications. iOS is the Company's multi-touch operating system that serves as the foundation for iOS devices. Devices running iOS are compatible with both Mac and Windows personal computers and Apple iCloud services. The Company offers iOS 10, which introduces the ability for Siri to do more by working with applications, updates messages, includes redesigned maps, photos, Apple music and news applications, and the home applications, which provides a way to manage home automation products in one place.
    macOS is the Company's Mac operating system and is built on an open-source uniplexed information and computing system (UNIX) based foundation and provides an intuitive and integrated computer experience. macOS Sierra incorporates Siri and Apple Pay on the Mac, provides continuity and document access across Apple devices and includes the memories feature in photos. watchOS is the Company's operating system for Apple Watch. The Company's watchOS three provides ability to launch applications instantly, navigation with the new Dock and new fitness and health capabilities for Apple Watch, including the Breathe applications designed to promote exercises for relaxation and stress reduction. tvOS is the Company's operating system for Apple TV. The tvOS operating system is based on the Company's iOS platform and enables developers to create applications and games specifically for Apple TV and deliver them to customers through the Apple TV App Store. The tvOS incorporates new Siri capabilities that allow searching across more applications and services.
    The Company's applications software includes iLife, iWork and other software, including Final Cut Pro, Logic Pro X and FileMaker Pro. iLife is the Company's consumer-oriented digital lifestyle software applications suite included with all Mac computers and features iMovie, a digital video editing applications, and GarageBand, a music creation application that allows users to play, record and create music. iWork is the Company's integrated productivity suite included with all Mac computers and is designed to help users create, present and publish documents through Pages, presentations through Keynote and spreadsheets through Numbers. The Company also has multi-touch versions of iLife and iWork applications designed specifically for use on iOS devices, which are available as free downloads for all new iOS devices.
    The iTunes Store, available for iOS devices, Mac and Windows personal computers and Apple TV, allows customers to purchase and download music and TV shows, rent or purchase movies and download free podcasts. The App Store, available for iOS devices, allows customers to discover and download applications and purchase in-applications content. The Mac applications Store, available for Mac computers, allows customers to discover, download and install Mac applications. The TV App Store allows customers access to applications and games specifically for the Apple TV. The iBooks Store, available for iOS devices and Mac computers, features e-books from major and independent publishers. Apple Music offers users a listening experience with on-demand radio stations that evolve based on a user's play or download activity and a subscription-based Internet streaming service that also provides access to the applications music library.
    iCloud is the Company's cloud service, which stores music, photos, contacts, calendars, mail, documents and more, keeping them up-to-date and available across multiple iOS devices, Mac and Windows personal computers and Apple TV. iCloud services include iCloud Drive, iCloud Photo Library, Family Sharing, Find My iPhone, iPad or Mac, Find My Friends, Notes, iCloud Keychain and iCloud Backup for iOS devices. AppleCare offers a range of support options for the Company's customers. These include assistance that is built into software products, printed and electronic product manuals, online support including comprehensive product information, technical assistance, the AppleCare Protection Plan (APP) and the AppleCare Protection Plan (AC+). AC+ is a fee-based service offering additional coverage under some circumstances for instances of accidental damage in addition to the services offered by APP and is available in certain countries for iPhone, iPad, AppleCare Watch and iPod. Apple Pay is the Company's mobile payment service available in certain countries that offers a private way to pay.
    Apple Pay allows users to pay for purchases in stores accepting contactless payments and to pay for purchases within participating applications on qualifying devices. Apple Pay accepts credit and debit cards across major card networks and also supports reward programs and store-issued credit and debit cards. The Company sells a variety of Apple-branded and third-party Mac-compatible and iOS-compatible accessories, including Apple TV, Apple Watch, Beats products, iPod, headphones, displays, storage devices, and various other connectivity and computing products and supplies. The Company offers AirPods, new wireless headphones that interact with Siri.",
    "name" = "Apple Inc",
    "ticker" = "AAPL.OQ",
    "url" = "https://www.reuters.com/finance/stocks/company-profile/AAPL.OQ"
  ),
  "jpmorgan" = list(
    "desc" = "JPMorgan Chase & Co. (JPMorgan Chase), incorporated on October 28, 1968, is a financial holding company. The Company is engaged in investment banking, financial services for consumers and small businesses, commercial banking, financial transaction processing and asset management. JPMorgan Chase's activities are organized into four business segments, as well as a Corporate segment. The Company's segments include Consumer & Community Banking, Corporate & Investment Bank, Commercial Banking, and Asset & Wealth Management. Its principal bank subsidiaries include JPMorgan Chase Bank, National Association (JPMorgan Chase Bank, N.A.), a national banking association, and Chase Bank USA, National Association (Chase Bank USA, N.A.), a national banking association that is the Company's credit card-issuing bank. JPMorgan Chase's principal nonbank subsidiary is J.P. Morgan Securities LLC (JPMorgan Securities), the United States investment banking firm. The bank and nonbank subsidiaries of JPMorgan Chase operate nationally, as well as through overseas branches and subsidiaries, representative offices and subsidiary foreign banks. The Company's principal operating subsidiary in the United Kingdom is J.P. Morgan Securities plc, a subsidiary of JPMorgan Chase Bank, N.A.
Consumer & Community Banking
    The Consumer & Community Banking segment offers services to consumers and businesses through bank branches, automatic teller machines (ATMs), online, mobile and telephone banking. It is organized into Consumer & Business Banking (including Consumer Banking/Chase Wealth Management and Business Banking), Mortgage Banking (including Mortgage Production, Mortgage Servicing and Real Estate Portfolios) and Card, Commerce Solutions & Auto. Consumer & Business Banking offers deposit and investment products and services to consumers, and lending, deposit, and cash management and payment solutions to small businesses. Mortgage Banking includes mortgage origination and servicing activities, as well as portfolios consisting of residential mortgages and home equity loans. Card, Commerce Solutions & Auto issues credit cards to consumers and small businesses, offers payment processing services to merchants, originates and services auto loans and leases, and services student loans.
    Corporate & Investment Bank
    The Corporate & Investment Bank segment, which consists of Banking and Markets & Investor Services, offers a suite of investment banking, market-making, prime brokerage, and treasury and securities products and services to a global client base of corporations, investors, financial institutions, government and municipal entities. Banking offers a range of investment banking products and services in all capital markets, including advising on corporate strategy and structure, capital-raising in equity and debt markets, as well as loan origination and syndication. Banking also includes Treasury Services, which provides transaction services, consisting of cash management and liquidity solutions. Markets & Investor Services is a global market-maker in cash securities and derivative instruments, and also offers risk management solutions, prime brokerage, and research. Markets & Investor Services also includes Securities Services, a global custodian that provides custody, fund accounting and administration, and securities lending products principally for asset managers, insurance companies and public and private investment funds.
    Commercial Banking
    The Commercial Banking segment delivers industry knowledge, local expertise and service to the United States and the United States multinational clients, including corporations, municipalities, financial institutions and non-profit entities. It provides financing to real estate investors and owners. It also provides financial solutions, including lending, treasury services, investment banking and asset management.
    Asset & Wealth Management
    The Asset & Wealth Management segment comprises investment and wealth management. Its clients include institutions, high-net-worth individuals and retail investors in markets throughout the world. It offers investment management across asset classes, including equities, fixed income, alternatives and money market funds. It also offers multi-asset investment management, providing solutions for a range of clients' investment needs. For Wealth Management clients, it also provides retirement products and services, brokerage and banking services, including trusts and estates, loans, mortgages and deposits.",
    "name" = "Jpmorgan Chase Financial Company LLC",
    "ticker" = "PPLN.P",
    "url" = "https://www.reuters.com/finance/stocks/company-profile/PPLN.P"
  )
)

# Write to disk
devtools::use_data(company_descriptions, overwrite = TRUE)
